name: Build and Test
on:
  release:
    types: [created]
jobs:
  publish-npm:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - run: pnpm version ${{ github.event.release.tag_name }}
      - run: pnpm i
      - run: pnpm build
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
